#!/usr/bin/env ruby

FLIPS = {
  'a' => "\u0250",
  'b' => 'q',
  'c' => "\u0254",
  'd' => 'p',
  'e' => "\u01DD",
  'f' => "\u025F",
  'g' => 'b',
  'h' => "\u0265",
  'i' => "\u0131\u0323",
  'j' => "\u0638",
  'k' => "\u029E",
  'l' => "\u05DF",
  'm' => "\u026F",
  'n' => 'u',
  'o' => 'o',
  'p' => 'd',
  'q' => 'b',
  'r' => "\u0279",
  's' => 's',
  't' => "\u0287",
  'u' => 'n',
  'v' => "\u028C",
  'w' => "\u028D",
  'x' => 'x',
  'y' => "\u028E",
  'z' => 'z',
  '[' => ']',
  ']' => '[',
  '(' => ')',
  ')' => '(',
  '{' => '}',
  '}' => '{',
  '?' => "\u00BF",
  "\u00BF" => '?',
  '!' => "\u00A1",
  "'" => ',',
  ',' => "'",
  '.' => "\u02D9",
  '_' => "\u203E",
  ';' => "\u061B",
  '9' => '6',
  '6' => '9'
}.freeze

def flip(text)
  text.downcase.chars.reverse.map { |c| FLIPS[c] || c }.join
end

input = ARGV.empty? ? gets : ARGV.join(' ')
print flip(input)
