#!/usr/bin/env ruby

def full_width(text)
  text
    .chars
    .map(&:ord)
    .each_with_object(0xfee0)
    .each_with_object(:+)
    .map(&:reduce)
    .pack('U*')
    .tr("\uff00", "\u3000")
end

input = ARGV.empty? ? gets : ARGV.join(' ')

print full_width(input)
